# Generated by Django 2.2.dev20180816134906 on 2018-08-28 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0014_remove_company_fax'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('second_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('egn', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=55)),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('salary', models.FloatField()),
                ('date_of_appointment', models.DateField()),
                ('date_of_dismiss', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.Company')),
                ('job_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hrs.JobPosition')),
            ],
            options={
                'permissions': (('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete')),
            },
        ),
    ]
