# Generated by Django 2.2.dev20180816134906 on 2018-08-28 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
    ]
