# Generated by Django 2.2.dev20180816134906 on 2018-08-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0002_remove_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='hrs.JobPosition'),
            preserve_default=False,
        ),
    ]
