# Generated by Django 2.2.dev20180816134906 on 2018-08-28 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0003_auto_20180828_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='job_position',
        ),
    ]
