# Generated by Django 2.2.dev20180816134906 on 2018-08-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0004_remove_employee_job_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hrs.JobPosition'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_dismiss',
            field=models.DateField(blank=True, default=None),
        ),
    ]
