# Generated by Django 2.2.dev20180816134906 on 2018-08-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0006_auto_20180828_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_dismiss',
            field=models.DateField(blank=True, null=True),
        ),
    ]
