# Generated by Django 2.2.dev20180816134906 on 2018-08-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_remove_company_fax'),
        ('hrs', '0007_auto_20180828_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.Company'),
        ),
    ]
