# Generated by Django 2.2.dev20180816134906 on 2018-08-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrs', '0008_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
