# Generated by Django 2.2.dev20180816134906 on 2018-08-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180825_2256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'permissions': (('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete'))},
        ),
    ]
