# Generated by Django 2.2.dev20180816134906 on 2018-08-28 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20180828_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MinValueValidator(15)]),
        ),
    ]
