# Generated by Django 2.2.dev20180816134906 on 2018-08-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20180828_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
