# Generated by Django 2.2.dev20180816134906 on 2018-08-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_auto_20180824_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('license_plate', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('purchase_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('company_owner', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='companies.Company')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('gasoline', 'Gasoline')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
