# Generated by Django 2.2.dev20180816134906 on 2018-08-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='company_owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='companies.Company'),
        ),
    ]
