# Generated by Django 2.2.dev20180816134906 on 2018-08-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_auto_20180826_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('d', 'Diesel'), ('g', 'Gasoline')], max_length=1),
        ),
    ]
