# Generated by Django 2.2.dev20180816134906 on 2018-08-28 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0003_auto_20180826_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'permissions': (('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete'))},
        ),
    ]
