# Generated by Django 2.2.dev20180816134906 on 2018-08-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0004_auto_20180828_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='company_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='companies.Company'),
        ),
    ]
