# Generated by Django 2.2.dev20180816134906 on 2018-08-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mrp', models.CharField(max_length=50)),
                ('vat', models.CharField(max_length=50)),
                ('idn', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=25)),
                ('fax', models.CharField(max_length=25)),
                ('iban', models.CharField(max_length=35)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
