# Generated by Django 2.2.dev20180816134906 on 2018-08-24 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='companies.Company'),
        ),
    ]
