# Generated by Django 2.2.dev20180816134906 on 2018-08-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_child'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
    ]
