# Generated by Django 2.2.dev20180816134906 on 2018-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_delete_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss', models.CharField(max_length=1)),
            ],
        ),
    ]
