# Generated by Django 2.2.dev20180816134906 on 2018-08-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_cc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cc',
        ),
    ]
