# Generated by Django 2.2.dev20180816134906 on 2018-08-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_delete_cc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('add_content', 'Add Content'),)},
        ),
    ]
