# Generated by Django 2.2.dev20180816134906 on 2018-08-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20180828_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='iban',
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
