# Generated by Django 2.2.dev20180816134906 on 2018-08-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_auto_20180828_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('add', 'Add'), ('edit', 'Edit'), ('delete', 'Delete'))},
        ),
    ]
