# Generated by Django 2.2.dev20180816134906 on 2018-08-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_auto_20180828_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='fax',
        ),
    ]
