# Generated by Django 2.2.dev20180816134906 on 2018-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20180826_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='model_class',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
